name: ImV
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch>=1.4
  - torchvision>=0.5
  - opencv
  - pywavelets
  - nb_conda_kernels
  - pip:
    - torchviz