name: cuda
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - opencv
  - pywavelets
  - nb_conda_kernels
  - pip:
    - scikit-image
    - pandas
    - pillow
    - tqdm
    - nbconvert